# Generated by Django 4.1.3 on 2022-11-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, help_text='Name of the tournament or match event', null=True)),
                ('site', models.CharField(blank=True, help_text='Location of the event. City, Region, COUNTRY', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, help_text='Playing round ordinal of the game within the event', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.chessevent')),
            ],
        ),
    ]
